source 'https://rubygems.org'

gem 'rails'
gem 'pg'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'bcrypt-ruby'
gem 'unicorn'
gem 'awesome_print'
gem 'twitter'
gem 'rails_12factor'
gem 'clockwork'
gem 'redcarpet'
gem 'dotenv-rails', :groups => [:development, :test]
